CREATE TABLE PESSOA (
	uid INTEGER, nome VARCHAR(20), email VARCHAR(40),
	senha VARCHAR(20), tipo BOOLEAN,

	PRIMARY KEY (uid)
);

CREATE TABLE PRODUTO (
	pid INTEGER, fid INTEGER, nome VARCHAR(40),
	descricao TEXT, capa TINYTEXT, qtd INTEGER,
	valor REAL, vendas INTEGER,

	PRIMARY KEY (pid, fid),
	FOREIGN KEY (fid) REFERENCES PESSOA(uid) ON DELETE CASCADE,
	FULLTEXT (nome)
);

CREATE TABLE HISTORICO (
	pid INTEGER, cid INTEGER, fid INTEGER,
	data DATE, qtd INTEGER, total REAL,

	PRIMARY KEY (pid, cid, fid),
	FOREIGN KEY (pid) REFERENCES PRODUTO(pid),
	FOREIGN KEY (cid) REFERENCES PESSOA(uid) ON DELETE CASCADE,
	FOREIGN KEY (fid) REFERENCES PESSOA(uid)
);

CREATE TABLE POSSUI_NO_CARRINHO (
	pid INTEGER, cid INTEGER, qtd INTEGER,

	PRIMARY KEY (pid, cid),
	FOREIGN KEY (pid) REFERENCES PRODUTO(pid) ON DELETE CASCADE,
	FOREIGN KEY (cid) REFERENCES PESSOA(uid) ON DELETE CASCADE
);

CREATE TABLE FOTO (
	pid INTEGER, url TINYTEXT,

	PRIMARY KEY (pid, url(255)),
	FOREIGN KEY (pid) REFERENCES PRODUTO(pid) ON DELETE CASCADE
);